package ab.configuration.constan;

public class ConstantResponse
{

    public static final String C_NOT_SUPPORTED_YET = "<!DOCTYPE html><html lang=\"en\"><head><title>500 Internal Server Error </title><style type=\"text/css\">::selection{ background-color: #E13300; color: white; }::moz-selection{ background-color: #E13300; color: white; }::webkit-selection{ background-color: #E13300; color: white; }body {\tbackground-color: #fff;\tmargin: 40px;\tfont: 13px/20px normal Helvetica, Arial, sans-serif;\tcolor: black;}a {\tcolor: #003399;\tbackground-color: transparent;\tfont-weight: normal;}h1 {\tcolor: #444;\tbackground-color: transparent;\tborder-bottom: 1px solid #D0D0D0;\tfont-size: 19px;\tfont-weight: normal;\tmargin: 0 0 14px 0;\tpadding: 14px 15px 10px 15px;}code {\tfont-family: Consolas, Monaco, Courier New, Courier, monospace;\tfont-size: 12px;\tbackground-color: #f9f9f9;\tborder: 1px solid #D0D0D0;\tcolor: #002166;\tdisplay: block;\tmargin: 14px 0 14px 0;\tpadding: 12px 10px 12px 10px;}#container {\tmargin: 10px;\tborder: 1px solid #D0D0D0;\t-webkit-box-shadow: 0 0 8px #D0D0D0;}p {\tmargin: 12px 15px 12px 15px;}</style></head><body>\t<div id='container'>\t\t<h1>500 Internal Server Error</h1>\t\t<p>Maaf, sistem operasi anda belum mendukung untuk Muntilan Webserver</p><p>Untuk sementara hanya tersedia untuk sistem operasi Microsoft Windows</p></div></body></html>";
    public static final String C_EXCEPTION = "EXCEPTION";
    public static final String notFound = "<!DOCTYPE html><html lang=\"en\"><head><title>404 Page Not Found</title><style type=\"text/css\">::selection{ background-color: #E13300; color: white; }::moz-selection{ background-color: #E13300; color: white; }::webkit-selection{ background-color: #E13300; color: white; }body {\tbackground-color: #fff;\tmargin: 40px;\tfont: 13px/20px normal Helvetica, Arial, sans-serif;\tcolor: black;}a {\tcolor: #003399;\tbackground-color: transparent;\tfont-weight: normal;}h1 {\tcolor: #444;\tbackground-color: transparent;\tborder-bottom: 1px solid #D0D0D0;\tfont-size: 19px;\tfont-weight: normal;\tmargin: 0 0 14px 0;\tpadding: 14px 15px 10px 15px;}code {\tfont-family: Consolas, Monaco, Courier New, Courier, monospace;\tfont-size: 12px;\tbackground-color: #f9f9f9;\tborder: 1px solid #D0D0D0;\tcolor: #002166;\tdisplay: block;\tmargin: 14px 0 14px 0;\tpadding: 12px 10px 12px 10px;}#container {\tmargin: 10px;\tborder: 1px solid #D0D0D0;\t-webkit-box-shadow: 0 0 8px #D0D0D0;}p {\tmargin: 12px 15px 12px 15px;}</style></head><body>\t<div id='container'>\t\t<h1>404 Page Not Found</h1>\t\t<p>The page you requested was not found.</p>\t</div></body></html>";

    public static String internalServerError(String titleException, String stackTrace)
    {
        return "<!DOCTYPE html><html lang=\"en\"><head><title>500 Internal Server Error</title><style type=\"text/css\">::selection{ background-color: #E13300; color: white; }::moz-selection{ background-color: #E13300; color: white; }::webkit-selection{ background-color: #E13300; color: white; }body {\tbackground-color: #fff;\tmargin: 40px;\tfont: 13px/20px normal Helvetica, Arial, sans-serif;\tcolor: black;}a {\tcolor: #003399;\tbackground-color: transparent;\tfont-weight: normal;}h1 {\tcolor: #444;\tbackground-color: transparent;\tborder-bottom: 1px solid #D0D0D0;\tfont-size: 19px;\tfont-weight: normal;\tmargin: 0 0 14px 0;\tpadding: 14px 15px 10px 15px;}code {\tfont-family: Consolas, Monaco, Courier New, Courier, monospace;\tfont-size: 12px;\tbackground-color: #f9f9f9;\tborder: 1px solid #D0D0D0;\tcolor: #002166;\tdisplay: block;\tmargin: 14px 0 14px 0;\tpadding: 12px 10px 12px 10px;}#container {\tmargin: 10px;\tborder: 1px solid #D0D0D0;\t-webkit-box-shadow: 0 0 8px #D0D0D0;}p {\tmargin: 12px 15px 12px 15px;}</style></head><body>\t<div id='container'>\t\t<h1>500 Internal Server Error</h1>\t\t<p>" + titleException + "</p>\t" + "</div>" + "<div id='container'>\t\t" + "\t\t" + "<p>" + stackTrace + "</p>\t" + "</div>" + "</body></html>";
    }
}